name: flutter_zepp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1
  http: ^1.1.0
  webview_flutter: ^4.4.1
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.1.14
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  lottie: ^2.6.0
  logger: ^2.0.2+1
  json_serializable: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/login/bg_dark.png
    - assets/images/login/bg_light.png
    - assets/images/login/logo.png
    - assets/images/login/login_method_apple.png 
    - assets/images/login/login_method_wechat.png 
    - assets/images/login/login_method_xiaomi.png

    - assets/images/tabbar/tabbar_icon_aura.png
    - assets/images/tabbar/tabbar_icon_aura_unselected.png
    - assets/images/tabbar/tabbar_icon_profile.png
    - assets/images/tabbar/tabbar_icon_profile_unselected.png
    - assets/images/tabbar/tabbar_icon_sleep.png
    - assets/images/tabbar/tabbar_icon_sleep_unselected.png
    - assets/images/tabbar/tabbar_icon_status.png
    - assets/images/tabbar/tabbar_icon_status_unselected.png
    - assets/images/tabbar/tabbar_icon_workout.png
    - assets/images/tabbar/tabbar_icon_workout_unselected.png
